apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - base/argocd-certificate.yaml
  - base/argocd-ingress.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/ha/install.yaml

components:
  - https://github.com/argoproj-labs/argocd-extensions/manifests

patches:
  - path: overlays/argocd-cm.yaml
  - path: overlays/argocd-cmd-params-cm.yaml
  - path: overlays/argocd-rbac-cm.yaml
  - path: overlays/argocd-server-service.yaml

images:
- name: quay.io/argoproj/argocd
  newName: ghcr.io/argoproj/argo-cd/argocd
  newTag: 3.5.0-82f71400
