config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/mattinm/argocd-apps.git
      targetRevision: main

applications:
  - name: cert-manager
