apiVersion: v1
kind: Secret
metadata:
  name: apps-repository
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/mattinm/argocd-apps.git
